// Factory patches.
//
// Ported from the source versions with the resonance values RE-DERIVED, not
// copied: those presets carried a mix of two scales — some values on 0..1 and
// some on a biquad's 0..25 Q — into a ladder whose feedback gain is 0..4. The
// "acid" patch asked for 18, i.e. k=72, eighteen times past self-oscillation.
// Every such value is set here on the one scale the filter actually has.

import type { SynthPatch } from "./types";

export const DEFAULT_PATCH: SynthPatch = {
  osc1Morph: 2, // sawtooth
  osc1Octave: 0,
  osc1Level: 0.7,
  osc2Morph: 2,
  osc2Detune: 7,
  osc2Level: 0.5,
  subLevel: 0,
  noiseLevel: 0,
  fmAmount: 0,
  ringAmount: 0,
  unisonVoices: 1,
  unisonDetune: 10,
  filterCutoff: 8000,
  filterResonance: 0.15,
  filterDrive: 1,
  filterKeyTrack: 0,
  filterAttack: 0.01,
  filterDecay: 0.3,
  filterSustain: 0.3,
  filterEnvAmount: 2000,
  ampAttack: 0.005,
  ampDecay: 0.3,
  ampSustain: 0.8,
  ampRelease: 0.3,
  lfo1Rate: 3,
  lfo1Amount: 0,
  lfo1Target: "cutoff",
  lfo2Rate: 4,
  lfo2Amount: 0,
  lfo2Target: "pitch",
  saturation: 0,
  chorusRate: 1.2,
  chorusDepth: 0,
  delayTime: 0.35,
  delayFeedback: 0.3,
  delayMix: 0,
  reverbDecay: 0.6,
  reverbMix: 0,
  compThreshold: -24,
  compRatio: 4,
  compMakeup: 0,
  volume: 0.5,
  stereoWidth: 0,
};

export interface Preset {
  id: string;
  name: string;
  /** One line on what the patch demonstrates. */
  note: string;
  patch: SynthPatch;
}

const from = (over: Partial<SynthPatch>): SynthPatch => ({ ...DEFAULT_PATCH, ...over });

export const PRESETS: Preset[] = [
  {
    id: "init",
    name: "Init",
    note: "Two saws a few cents apart — the plain starting point.",
    patch: DEFAULT_PATCH,
  },
  {
    id: "acid",
    name: "Acid",
    note: "High resonance plus a fast filter envelope: the sound the ladder's saturated feedback exists for.",
    patch: from({
      osc1Morph: 3,
      osc1Octave: -1,
      osc1Level: 0.9,
      osc2Detune: 5,
      osc2Level: 0.4,
      subLevel: 0.35,
      filterCutoff: 250,
      filterResonance: 0.85,
      filterDrive: 1.4,
      filterKeyTrack: 0.3,
      filterAttack: 0,
      filterDecay: 0.14,
      filterSustain: 0,
      filterEnvAmount: 5200,
      ampAttack: 0,
      ampDecay: 0.15,
      ampSustain: 0.3,
      ampRelease: 0.08,
      saturation: 0.3,
      delayMix: 0.22,
      delayFeedback: 0.4,
      compThreshold: -18,
      compMakeup: 3,
      volume: 0.45,
    }),
  },
  {
    id: "pad",
    name: "Pad",
    note: "Four unison voices, slow envelopes, wide chorus into a long plate.",
    patch: from({
      osc1Morph: 2.3,
      osc2Morph: 2.5,
      osc2Detune: 12,
      osc2Level: 0.6,
      subLevel: 0.15,
      unisonVoices: 4,
      unisonDetune: 15,
      filterCutoff: 3000,
      filterResonance: 0.2,
      filterAttack: 0.8,
      filterDecay: 1,
      filterSustain: 0.8,
      filterEnvAmount: 1500,
      ampAttack: 0.8,
      ampDecay: 0.5,
      ampSustain: 0.8,
      ampRelease: 1.5,
      lfo1Rate: 0.5,
      lfo1Amount: 0.15,
      chorusRate: 0.8,
      chorusDepth: 0.6,
      delayMix: 0.2,
      reverbDecay: 0.85,
      reverbMix: 0.45,
      compThreshold: -30,
      compRatio: 2,
      compMakeup: 2,
      volume: 0.4,
      stereoWidth: 0.6,
    }),
  },
  {
    id: "bell",
    name: "Bell",
    note: "FM at a non-integer ratio gives inharmonic partials — the metallic part of a bell.",
    patch: from({
      osc1Morph: 0,
      osc1Octave: 1,
      osc1Level: 0.8,
      osc2Morph: 0,
      osc2Detune: 3,
      osc2Level: 0.35,
      fmAmount: 180,
      filterCutoff: 12000,
      filterResonance: 0.1,
      filterAttack: 0,
      filterDecay: 0.8,
      filterSustain: 0,
      filterEnvAmount: 5000,
      ampAttack: 0,
      ampDecay: 0.9,
      ampSustain: 0,
      ampRelease: 0.9,
      unisonVoices: 2,
      unisonDetune: 8,
      delayMix: 0.25,
      reverbDecay: 0.8,
      reverbMix: 0.4,
      compThreshold: -30,
      compRatio: 2,
      compMakeup: 4,
      stereoWidth: 0.4,
    }),
  },
  {
    id: "pluck",
    name: "Pluck",
    note: "Zero attack, short decay, filter tracking the keyboard — energy leaves fast, as it does on a string.",
    patch: from({
      osc2Morph: 3,
      osc2Detune: 5,
      osc2Level: 0.3,
      noiseLevel: 0.06,
      filterCutoff: 6000,
      filterResonance: 0.35,
      filterKeyTrack: 0.5,
      filterAttack: 0,
      filterDecay: 0.06,
      filterSustain: 0,
      filterEnvAmount: 8000,
      ampAttack: 0,
      ampDecay: 0.13,
      ampSustain: 0,
      ampRelease: 0.2,
      saturation: 0.12,
      delayTime: 0.25,
      delayMix: 0.18,
      reverbDecay: 0.5,
      reverbMix: 0.25,
      compThreshold: -20,
      compMakeup: 3,
    }),
  },
  {
    id: "wobble",
    name: "Wobble",
    note: "LFO straight onto the cutoff at depth — the filter is the instrument here.",
    patch: from({
      osc1Octave: -1,
      osc1Level: 0.8,
      osc2Detune: 10,
      osc2Level: 0.7,
      subLevel: 0.3,
      filterCutoff: 400,
      filterResonance: 0.7,
      filterDrive: 2,
      filterEnvAmount: 1200,
      ampAttack: 0.01,
      ampDecay: 0.2,
      ampSustain: 0.7,
      lfo1Rate: 2,
      lfo1Amount: 0.85,
      lfo1Target: "cutoff",
      saturation: 0.4,
      compThreshold: -18,
      compRatio: 6,
      compMakeup: 4,
      volume: 0.4,
    }),
  },
  {
    id: "strings",
    name: "Strings",
    note: "Six unison voices spread wide — the ensemble effect is just many slightly detuned copies.",
    patch: from({
      osc1Morph: 2.15,
      osc2Morph: 2.15,
      osc2Detune: 10,
      unisonVoices: 6,
      unisonDetune: 18,
      filterCutoff: 4000,
      filterResonance: 0.15,
      filterKeyTrack: 0.2,
      filterAttack: 0.5,
      filterDecay: 0.8,
      filterSustain: 0.7,
      filterEnvAmount: 1000,
      ampAttack: 0.5,
      ampDecay: 0.3,
      ampSustain: 0.85,
      ampRelease: 1.2,
      lfo1Rate: 1,
      lfo1Amount: 0.1,
      chorusRate: 0.6,
      chorusDepth: 0.5,
      delayMix: 0.1,
      reverbDecay: 0.85,
      reverbMix: 0.45,
      compThreshold: -28,
      compRatio: 2,
      compMakeup: 2,
      volume: 0.38,
      stereoWidth: 0.75,
    }),
  },
  {
    id: "lead",
    name: "Lead",
    note: "A little FM for bite, moderate resonance, and enough delay to sit forward.",
    patch: from({
      osc1Morph: 3,
      osc2Detune: 8,
      fmAmount: 18,
      unisonVoices: 2,
      unisonDetune: 12,
      filterCutoff: 6000,
      filterResonance: 0.4,
      filterDrive: 1.3,
      filterKeyTrack: 0.2,
      filterEnvAmount: 2000,
      ampAttack: 0.01,
      ampDecay: 0.2,
      ampSustain: 0.7,
      ampRelease: 0.2,
      lfo1Rate: 5,
      lfo1Amount: 0.12,
      lfo1Target: "pitch",
      saturation: 0.2,
      chorusDepth: 0.35,
      delayTime: 0.3,
      delayFeedback: 0.35,
      delayMix: 0.25,
      reverbMix: 0.2,
      compThreshold: -18,
      compMakeup: 3,
      stereoWidth: 0.3,
    }),
  },
  {
    id: "organ",
    name: "Organ",
    note: "Sines plus a sub, almost no envelope — the filter stays out of the way.",
    patch: from({
      osc1Morph: 0,
      osc1Level: 0.45,
      osc2Morph: 0,
      osc2Detune: 0,
      osc2Level: 0.3,
      subLevel: 0.28,
      unisonVoices: 3,
      unisonDetune: 5,
      filterCutoff: 10000,
      filterResonance: 0.05,
      filterEnvAmount: 0,
      ampAttack: 0.006,
      ampDecay: 0.05,
      ampSustain: 0.9,
      ampRelease: 0.12,
      lfo1Rate: 6,
      lfo1Amount: 0.08,
      lfo1Target: "volume",
      chorusRate: 0.7,
      chorusDepth: 0.5,
      reverbDecay: 0.7,
      reverbMix: 0.28,
      compThreshold: -24,
      compRatio: 3,
      compMakeup: 2,
      stereoWidth: 0.45,
    }),
  },
  {
    id: "brass",
    name: "Brass",
    note: "The filter opens a beat after the note starts, which is what makes a brass attack read as brass.",
    patch: from({
      osc1Morph: 2.2,
      osc2Morph: 2.3,
      osc2Detune: 5,
      osc2Level: 0.7,
      noiseLevel: 0.03,
      unisonVoices: 3,
      unisonDetune: 8,
      filterCutoff: 2500,
      filterResonance: 0.3,
      filterKeyTrack: 0.3,
      filterAttack: 0.09,
      filterDecay: 0.2,
      filterSustain: 0.8,
      filterEnvAmount: 3200,
      ampAttack: 0.08,
      ampDecay: 0.2,
      ampSustain: 0.8,
      ampRelease: 0.3,
      lfo1Rate: 5,
      lfo1Amount: 0.12,
      lfo1Target: "pitch",
      saturation: 0.15,
      chorusDepth: 0.3,
      delayMix: 0.1,
      reverbMix: 0.2,
      compThreshold: -20,
      compMakeup: 3,
      volume: 0.42,
      stereoWidth: 0.35,
    }),
  },
];

export function getPreset(id: string): Preset | undefined {
  return PRESETS.find((p) => p.id === id);
}
