import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { OUTFILE, buildWorklet } from "../../scripts/build-worklet";

describe("the worklet artifact cannot drift from its source", () => {
  it("public/synth-worklet.js exists", () => {
    // Generated by `npm run build:worklet`, which predev and prebuild run
    // automatically. If this fails, run it.
    expect(existsSync(OUTFILE), `${OUTFILE} is missing — run \`npm run build:worklet\``).toBe(true);
  });

  it("matches a fresh bundle of lib/synth-engine", async () => {
    // The whole reason for bundling rather than hand-writing the worklet: the
    // audio thread must run the same code the tests run. A stale artifact would
    // mean the browser plays one engine while the suite verifies another, which
    // is exactly the drift every other guard in this repo exists to prevent.
    const committed = readFileSync(OUTFILE, "utf8");
    const fresh = await buildWorklet(false);
    expect(committed, "public/synth-worklet.js is stale — run `npm run build:worklet`").toBe(fresh);
  }, 30_000);

  it("is a self-contained classic script — no imports survive into the worklet realm", () => {
    // An AudioWorklet module has no module loader and cannot resolve bare
    // specifiers, so an import statement here would fail silently at addModule.
    const code = readFileSync(OUTFILE, "utf8");
    expect(code).not.toMatch(/^\s*import\s/m);
    expect(code).not.toMatch(/^\s*export\s/m);
    expect(code).not.toMatch(/\brequire\(/);
  });

  it("registers the processor name the page loads", () => {
    const code = readFileSync(OUTFILE, "utf8");
    expect(code).toContain('registerProcessor("synth-processor"');
  });

  it("carries the engine itself, not a reference to it", () => {
    // Spot-check that the DSP was actually inlined rather than left as an
    // unresolved import.
    const code = readFileSync(OUTFILE, "utf8");
    for (const marker of ["PlateReverb", "LadderFilter", "Envelope", "blep"]) {
      expect(code, `bundle is missing ${marker}`).toContain(marker);
    }
  });

  it("says it is generated, so nobody edits it by hand", () => {
    expect(readFileSync(OUTFILE, "utf8")).toMatch(/GENERATED FILE/);
  });
});
