import type { BookType, BookTypeKey } from "./types";

export const BOOK_TYPES: Record<BookTypeKey, BookType> = {
  novel: {
    icon: "📖",
    label: "Novel / Fiction",
    sub_genres: ["literary", "thriller", "romance", "sci-fi", "fantasy", "mystery", "horror", "historical", "adventure", "young_adult"],
    engine: "FictionEngine",
    default_chapters: 25,
    default_words: 4000,
    structures: ["three_act", "heros_journey", "kishotenketsu", "nonlinear"],
    analysis_focus: ["show_vs_tell", "voice_consistency", "sensory", "pacing", "emotion", "character_arc"],
    pipeline_stages: [
      { id: "ctx", name: "Global Context", icon: "🌐", desc: "Assemble genre, world, characters, themes" },
      { id: "arch", name: "Book Architecture", icon: "🏗️", desc: "Three-act structure, character arcs, tension map" },
      { id: "chapter", name: "Chapter Prompt", icon: "📝", desc: "Generate scene-by-scene chapter prompts" },
      { id: "write", name: "LLM Write", icon: "🤖", desc: "Draft generation via LLM" },
      { id: "analyze", name: "Prose Analysis", icon: "🔬", desc: "Show/tell, voice, sensory, pacing analysis" },
      { id: "revise", name: "Revision Loop", icon: "🔄", desc: "Auto-revise until quality gate passes" },
      { id: "assemble", name: "Final Assembly", icon: "📚", desc: "Compile complete book" },
    ],
  },
  nonfiction: {
    icon: "📚",
    label: "Non-Fiction",
    sub_genres: ["self_help", "business", "science", "psychology", "history", "biography", "philosophy", "health", "technology", "social_science"],
    engine: "NonFictionEngine",
    default_chapters: 16,
    default_words: 3500,
    structures: ["problem_solution", "chronological", "spiral", "process_steps", "comparative", "theory_practice", "case_driven", "question_answer", "thematic", "principle_based"],
    analysis_focus: ["argument_strength", "evidence", "clarity", "logic", "pedagogy"],
    pipeline_stages: [
      { id: "ctx", name: "Global Context", icon: "🌐", desc: "Assemble thesis, framework, sources, voice" },
      { id: "arch", name: "Book Architecture", icon: "🏗️", desc: "Thesis decomposition, argument flow, evidence plan" },
      { id: "chapter", name: "Chapter Prompt", icon: "📝", desc: "Type-aware chapter prompts" },
      { id: "write", name: "LLM Write", icon: "🤖", desc: "Draft generation via LLM" },
      { id: "analyze", name: "Argument Analysis", icon: "🔬", desc: "Claims, evidence, clarity, logic analysis" },
      { id: "revise", name: "Revision Loop", icon: "🔄", desc: "Strengthen evidence, fix logic, add pedagogy" },
      { id: "assemble", name: "Final Assembly", icon: "📚", desc: "Compile + verify thesis fully proven" },
    ],
  },
  howto: {
    icon: "🔧",
    label: "How-To / Guide",
    sub_genres: ["diy", "crafts", "technology", "finance", "career", "fitness", "cooking", "gardening", "home_repair", "personal_dev"],
    engine: "HowToEngine",
    default_chapters: 12,
    default_words: 2500,
    structures: ["sequential_steps", "skill_levels", "project_based", "problem_solution"],
    analysis_focus: ["clarity", "actionability", "step_completeness", "safety", "practicality"],
    pipeline_stages: [
      { id: "ctx", name: "Global Context", icon: "🌐", desc: "Skill scope, prerequisites, outcomes" },
      { id: "arch", name: "Book Architecture", icon: "🏗️", desc: "Skill progression, project breakdown" },
      { id: "chapter", name: "Chapter Prompt", icon: "📝", desc: "Step-by-step chapter prompts" },
      { id: "write", name: "LLM Write", icon: "🤖", desc: "Draft generation via LLM" },
      { id: "analyze", name: "Clarity Analysis", icon: "🔬", desc: "Step completeness, actionability check" },
      { id: "revise", name: "Revision Loop", icon: "🔄", desc: "Fix missing steps, add safety notes" },
      { id: "assemble", name: "Final Assembly", icon: "📚", desc: "Compile with tool lists and appendices" },
    ],
  },
  kids: {
    icon: "🧸",
    label: "Children's Book",
    sub_genres: ["picture_book", "early_reader", "chapter_book", "middle_grade", "educational", "bedtime", "adventure", "moral_stories", "activity_book", "bilingual_kids"],
    engine: "KidsEngine",
    default_chapters: 10,
    default_words: 800,
    structures: ["simple_three_act", "repetition", "cumulative", "circular", "question_answer"],
    analysis_focus: ["age_appropriateness", "vocabulary", "engagement", "illustration_notes", "read_aloud_flow"],
    pipeline_stages: [
      { id: "ctx", name: "Global Context", icon: "🌐", desc: "Age group, theme, vocabulary level" },
      { id: "arch", name: "Book Architecture", icon: "🏗️", desc: "Story arc, character design, page layout" },
      { id: "chapter", name: "Page/Chapter Prompt", icon: "📝", desc: "Scene-by-scene with illustration notes" },
      { id: "write", name: "LLM Write", icon: "🤖", desc: "Draft generation via LLM" },
      { id: "analyze", name: "Age Check Analysis", icon: "🔬", desc: "Vocabulary, length, engagement analysis" },
      { id: "revise", name: "Revision Loop", icon: "🔄", desc: "Simplify language, enhance rhythm" },
      { id: "assemble", name: "Final Assembly", icon: "📚", desc: "Compile with illustration guide" },
    ],
  },
  cookbook: {
    icon: "🍳",
    label: "Cookbook",
    sub_genres: ["thai_cuisine", "baking", "healthy", "quick_meals", "vegetarian", "desserts", "street_food", "regional", "fusion", "meal_prep"],
    engine: "CookbookEngine",
    default_chapters: 10,
    default_words: 2000,
    structures: ["course_order", "cuisine_journey", "skill_progression", "seasonal", "theme_based"],
    analysis_focus: ["recipe_clarity", "ingredient_accuracy", "timing", "technique_explanation", "safety"],
    pipeline_stages: [
      { id: "ctx", name: "Global Context", icon: "🌐", desc: "Cuisine scope, skill level, dietary focus" },
      { id: "arch", name: "Book Architecture", icon: "🏗️", desc: "Chapter grouping, recipe selection" },
      { id: "chapter", name: "Chapter Prompt", icon: "📝", desc: "Recipe cluster prompts with stories" },
      { id: "write", name: "LLM Write", icon: "🤖", desc: "Draft generation via LLM" },
      { id: "analyze", name: "Recipe Analysis", icon: "🔬", desc: "Clarity, completeness, accuracy" },
      { id: "revise", name: "Revision Loop", icon: "🔄", desc: "Fix measurements, add tips" },
      { id: "assemble", name: "Final Assembly", icon: "📚", desc: "Compile with index and glossary" },
    ],
  },
  textbook: {
    icon: "🎓",
    label: "Textbook / Academic",
    sub_genres: ["mathematics", "science", "language", "history", "computer_science", "economics", "law", "medicine", "engineering", "arts"],
    engine: "TextbookEngine",
    default_chapters: 12,
    default_words: 5000,
    structures: ["prerequisite_chain", "concept_spiral", "modular", "theory_lab"],
    analysis_focus: ["accuracy", "pedagogy", "progression", "assessment", "exercises"],
    pipeline_stages: [
      { id: "ctx", name: "Global Context", icon: "🌐", desc: "Curriculum scope, level, standards" },
      { id: "arch", name: "Book Architecture", icon: "🏗️", desc: "Concept dependency graph, assessment plan" },
      { id: "chapter", name: "Chapter Prompt", icon: "📝", desc: "Lesson prompts with exercises" },
      { id: "write", name: "LLM Write", icon: "🤖", desc: "Draft generation via LLM" },
      { id: "analyze", name: "Academic Analysis", icon: "🔬", desc: "Accuracy, pedagogy, progression" },
      { id: "revise", name: "Revision Loop", icon: "🔄", desc: "Fix errors, add exercises" },
      { id: "assemble", name: "Final Assembly", icon: "📚", desc: "Compile with answer keys, index" },
    ],
  },
  memoir: {
    icon: "🖊️",
    label: "Memoir / Biography",
    sub_genres: ["personal_memoir", "celebrity", "historical_figure", "family", "travel", "survival", "creative_life", "business_leader", "athlete", "spiritual"],
    engine: "MemoirEngine",
    default_chapters: 20,
    default_words: 3500,
    structures: ["chronological", "thematic", "flashback", "episodic", "coming_of_age"],
    analysis_focus: ["authenticity", "emotional_truth", "narrative_arc", "voice", "scene_craft"],
    pipeline_stages: [
      { id: "ctx", name: "Global Context", icon: "🌐", desc: "Life scope, themes, voice" },
      { id: "arch", name: "Book Architecture", icon: "🏗️", desc: "Timeline, theme threading, arc" },
      { id: "chapter", name: "Chapter Prompt", icon: "📝", desc: "Episode/milestone prompts" },
      { id: "write", name: "LLM Write", icon: "🤖", desc: "Draft generation via LLM" },
      { id: "analyze", name: "Voice Analysis", icon: "🔬", desc: "Authenticity, emotion, narrative" },
      { id: "revise", name: "Revision Loop", icon: "🔄", desc: "Deepen emotion, sharpen scenes" },
      { id: "assemble", name: "Final Assembly", icon: "📚", desc: "Compile complete memoir" },
    ],
  },
  poetry: {
    icon: "🌸",
    label: "Poetry Collection",
    sub_genres: ["free_verse", "sonnets", "haiku", "narrative_poetry", "spoken_word", "prose_poetry", "ekphrastic", "confessional", "nature", "experimental"],
    engine: "PoetryEngine",
    default_chapters: 30,
    default_words: 200,
    structures: ["thematic_sections", "chronological", "mosaic", "call_response"],
    analysis_focus: ["imagery", "rhythm", "emotion", "economy", "sound"],
    pipeline_stages: [
      { id: "ctx", name: "Global Context", icon: "🌐", desc: "Theme, style, voice, forms" },
      { id: "arch", name: "Collection Architecture", icon: "🏗️", desc: "Section design, poem sequence" },
      { id: "chapter", name: "Poem Prompt", icon: "📝", desc: "Individual poem instructions" },
      { id: "write", name: "LLM Write", icon: "🤖", desc: "Draft generation via LLM" },
      { id: "analyze", name: "Poem Analysis", icon: "🔬", desc: "Imagery, rhythm, impact" },
      { id: "assemble", name: "Final Assembly", icon: "📚", desc: "Compile collection" },
    ],
  },
};

export const isFictionType = (t: BookTypeKey) => t === "novel" || t === "memoir" || t === "kids" || t === "poetry";
