// ╔══════════════════════════════════════════════════════════════════╗
// ║  THAI CARD METADATA — data only.                                  ║
// ║  Split out of th.ts for the same reason catalog-meta.ts was split ║
// ║  out of modules.ts: a page needing a Thai module DESCRIPTION was  ║
// ║  importing th.ts, which carries every Thai prompt builder.        ║
// ╚══════════════════════════════════════════════════════════════════╝

export const TH_META: Record<string, { description: string; usage: string }> = {
  MASTER: { description: "system prompt หลักสำหรับทุกเซสชัน", usage: "ตั้งเป็น system prompt ก่อนเขียนทุกบท" },
  OVERVIEW: { description: "วางแผนทั้งเล่ม", usage: "ส่งครั้งเดียวก่อนเขียนบทที่ 1" },
  ANALYSIS: { description: "วิเคราะห์คุณภาพดราฟต์แต่ละบท", usage: "ส่งพร้อมดราฟต์หลังเขียนแต่ละบท" },
  REVISION: { description: "แก้บทตามผลวิเคราะห์", usage: "ส่งพร้อมดราฟต์ + ผลวิเคราะห์" },
  FRONT_MATTER: { description: "หน้าปกใน คำอุทิศ สารบัญ คำนำ", usage: "สร้างหลังเขียนครบทุกบท" },
  BACK_MATTER: { description: "ภาคผนวก บรรณานุกรม ดัชนี", usage: "สร้างหลังส่วนหน้าเล่ม" },
  FEEDBACK: { description: "วิเคราะห์บทที่จบเพื่อสรุปให้บทถัดไป", usage: "ส่งหลังจบแต่ละบท" },
  GENRE_CORE: { description: "ล็อกคำสัญญาต่อคนอ่าน ขนบ และกับดักของแนวเรื่อง ก่อนวางโครง", usage: "รันก่อนสุด — ก่อน Outline — เพื่อจับสิ่งที่คนอ่านแนวนี้คาดหวัง" },
  STRUCTURE: { description: "โครงเรื่องรายบท (Save the Cat / Hero's Journey / Kishōtenketsu ฯลฯ)", usage: "รันก่อนเขียนเพื่อวางแผนทั้งเล่ม" },
  VOICE_SHEET: { description: "เสียงเฉพาะตัวของแต่ละตัวละคร", usage: "กรอกตัวละคร แล้ววางผลในพรอมป์ตบท" },
  CHAR_ARC: { description: "เส้นทางตัวละคร (ความเชื่อผิด vs ความจริง)", usage: "รันหลังโครงเรื่อง ก่อนเขียน" },
  WORLD_CODEX: { description: "story bible + ตรวจความต่อเนื่องรายบท", usage: "สร้างครั้งเดียว แล้วตรวจทุกบทใหม่" },
  SCENE: { description: "โครงฉากแบบ Scene/Sequel", usage: "ใช้เมื่อบทต้องการฉากที่แน่น" },
  DIALOGUE: { description: "action beat, subtext, ตัด tag เกิน", usage: "ส่งบทสนทนาเพื่อขัดเกลา" },
  FACT_CHECK: { description: "ตรวจทุกข้ออ้าง ห้ามแต่งอ้างอิง", usage: "ส่งดราฟต์สารคดีแต่ละบท" },
  ARG_MAP: { description: "แผนผัง Toulmin + โต้แย้งอย่างเป็นธรรม", usage: "รันกับข้อโต้แย้งหลักของบท" },
  EVIDENCE: { description: "จัดเกรดหลักฐาน + รายงานช่องโหว่", usage: "ส่งดราฟต์เพื่อตรวจหลักฐาน" },
  PEDAGOGY: { description: "objective Bloom + ตัวอย่าง + แบบฝึก", usage: "รันต่อบทสำหรับตำรา/how-to" },
  CASE_STUDY: { description: "กรณีศึกษาแบบ SPAR", usage: "ใช้ทำแนวคิดให้เป็นรูปธรรม" },
  VOICE_FP: { description: "สกัดชีตสไตล์จากงานตัวอย่าง", usage: "รันครั้งเดียวพร้อมตัวอย่าง ใช้ซ้ำทุกบท" },
  ANTI_SLOP: { description: "กำจัด AI slop แปรจังหวะ ทำให้รูปธรรม", usage: "ส่งดราฟต์เพื่อลบความกลาง ๆ" },
  READABILITY: { description: "รายงาน Flesch-Kincaid + เขียนใหม่คุมระดับ", usage: "ส่งดราฟต์ + ระดับเป้าหมาย" },
  LINE_EDIT: { description: "คำกรอง คำขยาย passive สำนวนเฝือ การซ้ำ", usage: "ส่งดราฟต์เพื่อแก้ระดับประโยค" },
  CUT_PASS: { description: "ตัด N คำพร้อมจำแนกทุกการตัด (ภาคสนาม: อธิบายเกิน ~32% เล่าซ้ำ ~26%) — พล็อต/การปูทางแตะไม่ได้", usage: "ส่งบทที่เขียนจบเพื่อให้กระชับ" },
  THAI_QA: { description: "ราชาศัพท์ ตัดประโยค ความสม่ำเสมอของคำทับศัพท์", usage: "ส่งต้นฉบับภาษาไทย" },
  WRITERS_ROOM: { description: "ห้องนักเขียนคนเดียว: blue sky → arcing → the board → break → audit ตามกระบวนการห้องทีวีที่บันทึกไว้จริง", usage: "รันก่อนวาง outline ซีซันหรือทั้งเล่ม" },
  SAGA_ARCHITECT: { description: "วางแกนเรื่องข้าม 3–9 season + บันได power/scale", usage: "รันก่อนเพื่อวางโครงงานหลาย season" },
  SAGA_SEASON: { description: "ออกแบบ season เดียวเชิงลึก (parts/plant/payoff/cliffhanger)", usage: "รันต่อ season หลังวางแกน" },
  SAGA_CONTINUITY: { description: "บัญชี SAGA STATE ข้าม season (canon/ตัวละคร/เวลา/การเปิดเผย)", usage: "ดูแลตลอดทุก season" },
  SAGA_BRIDGE: { description: "สะพานเชื่อม season: recap + hook ค้าง + ยกระดับ + เปิดเรื่องใหม่", usage: "รันระหว่าง season" },
  DIALECT_ISAN: { description: "แปลงบทพูดเป็นสำเนียงอีสาน + glossary คำถิ่น", usage: "วางต้นฉบับไทยกลางเพื่อแปลง" },
  DIALECT_NORTH: { description: "แปลงบทพูดเป็นคำเมือง (เหนือ/ล้านนา) + glossary", usage: "วางต้นฉบับไทยกลางเพื่อแปลง" },
  DIALECT_SOUTH: { description: "แปลงบทพูดเป็นสำเนียงใต้ + glossary", usage: "วางต้นฉบับไทยกลางเพื่อแปลง" },
  COVER_ART: { description: "คอนเซ็ปต์ปก 2 แบบ + prompt สำหรับ Midjourney/DALL·E·SD", usage: "รันเพื่อขอ prompt ปกหนังสือ" },
  TITLE: { description: "ชื่อเรื่อง+ชื่อรอง 10 แบบ (เล็ง keyword)", usage: "รันเพื่อหาตำแหน่ง/ชื่อ" },
  BLURB: { description: "คำโปรยปกหลัง + HTML สำหรับ Amazon", usage: "รันเพื่อเขียนคำบรรยายขาย" },
  KDP_META: { description: "keyword 7 + หมวด 3 + A+ hook", usage: "รันก่อนตีพิมพ์บน KDP" },
  SUBMISSION: { description: "query + synopsis + comp + ประวัติผู้เขียน", usage: "รันเพื่อส่งสำนักพิมพ์" },
  RECAP: { description: "สรุปต่อเนื่องแบบ chain-of-density", usage: "อัปเดตหลังแต่ละบท ใส่ต้นบทถัดไป" },
  BRAINSTORM: { description: "ระดมไอเดียหลากหลาย (verbalized sampling)", usage: "ใช้กับชื่อ จุดพลิก ชื่อตัวละคร hook" },
  ANTI_SAFE: { description: "ทำลายความปลอดภัยของ AI ยกเดิมพันจริง แบนคำคลิเชไทย", usage: "ส่งดราฟต์เพื่อทำให้เสี่ยงขึ้น" },
  SENSORY: { description: "ตรวจ 5 สัมผัสรายฉาก (≥3) + เติมรายละเอียดรูปธรรม", usage: "ส่งดราฟต์เพื่อลงประสาทสัมผัส" },
  HARD_SF: { description: "ตรวจพรีมิสไซไฟกับฟิสิกส์ 7 ข้อที่ต่อรองไม่ได้ แล้วขุดฉากที่ข้อจำกัดบังคับให้เกิด", usage: "ส่งพรีมิสไซไฟเพื่อให้ข้อจำกัดสร้างดราม่า" },
  THAI_SOUND: { description: "ชั้นเสียงร้อยแก้วไทย: คำซ้อนเพื่อเสียง สัมผัสใน คำซ้ำ ระดับภาษา บททดสอบอ่านออกเสียง", usage: "ส่งร้อยแก้วไทยเพื่อปรับจังหวะและความไพเราะ" },
  IMMERSION: { description: "เขียนฉากใหม่แบบ deep POV: ปักหมุดเร็ว ตัดกริยากรอง เติมความคิดภายใน เปิดปมค้าง จบด้วยแรงส่ง", usage: "ส่งฉากเพื่อดึงผู้อ่านเข้าไปข้างใน" },
  HOOK_CRAFT: { description: "ศาสตร์ hook ท้ายตอน (5 ประเภท + hybrid) และความยับยั้ง — almost moment, สิ่งที่เขาไม่ทำ, ร่างกายทรยศทีหลัง", usage: "ส่งตอนจบของบทเพื่อทำ hook ให้คม (หรือเขียนใหม่)" },
  PSYCH_ARC: { description: "จิตวิทยาความผูกพันเป็นเครื่องทำนายพฤติกรรม, เส้นทาง earned security (ช้า กำเริบได้), และฉากซ่อมแซม 3 ประเภท", usage: "ใช้ตอนออกแบบหรือตรวจเส้นความสัมพันธ์ slow burn" },
  QUIET_SCENE: { description: "ฉากที่พูดโดยไม่ใช้บทสนทนา: prosody (เทียบฐานเดิม เสียงแตกช้า), จัดฉาก co-regulation 5 จังหวะ, ระยะห่าง/จังหวะ/วัตถุ, การซ่อมแบบเงียบ", usage: "ส่งฉากอารมณ์ที่บทสนทนาน้อยเพื่อเขียนหรือขัดให้คม" },
  TRANSLATE: { description: "แปลซื่อสัตย์: คัมภีร์ canon + ล็อกศัพท์ + ข้อห้าม + micro-chunking กัน AI มโน/ไหลค่าเฉลี่ย", usage: "ใช้แปลข้อความ (เช่น ไทย→อังกฤษ ลง Royal Road) อย่างตรงต้นฉบับ" },
  SCENE_ART: { description: "แปลงฉากเป็น image prompt เข้าชุด (สไตล์/ซับเจกต์/ฉาก/อารมณ์/องค์ประกอบ + negative)", usage: "ส่งฉากเพื่อได้ prompt ภาพ (คุณรัน Midjourney/SD เอง)" },
  CHAR_CHAT: { description: "สร้าง system prompt คุยกับตัวละครแบบคง canon+เสียง มีกันสปอยล์/ขอบเขตความรู้", usage: "กรอกจากคัมภีร์ตัวละคร แล้วรันใน LLM ของคุณเพื่อแชตในโลกเรื่อง" },
  CONFLICT_MAP: { description: "เส้นความตึงรายฉาก + แก้จุดราบ", usage: "ส่งดราฟต์เพื่อทำแผนผังความตึง" },
  QUALITY_GATE: { description: "ด่านผ่าน/ไม่ผ่านก่อนตีพิมพ์: ต่อเนื่อง สัมผัส anti-safe เสียง ไทย", usage: "รันกับบทที่เสร็จก่อนไปต่อ" },
  SERIES_BIBLE: { description: "บัญชี canon ข้ามเล่ม: ตัวละคร/โลก/เส้นเวลา/การเปิดเผย/ปมค้าง + ตรวจต่อเนื่องรายเล่ม", usage: "ดูแลตลอดซีรีส์หลายเล่ม รันใหม่ทุกเล่ม" },
  AGENT_ORCHESTRATOR: { description: "ผู้ประสานงาน swarm: มอบหมาย+ตรวจสอบ ตารางคลื่น", usage: "ใช้เป็น system prompt ของตัวประสานงาน" },
  AGENT_RESEARCH: { description: "niche, usp, comps, keywords (JSON)", usage: "system prompt เอเจนต์เฟส 1" },
  AGENT_BIBLE: { description: "ตัวละคร โลก style card glossary (JSON)", usage: "system prompt เอเจนต์เฟส 2" },
  AGENT_ARCHITECT: { description: "arc map + โครงบท/ฉาก (JSON)", usage: "system prompt เอเจนต์เฟส 3" },
  AGENT_WRITER: { description: "เขียนหนึ่งฉากจาก spec + bible (JSON)", usage: "system prompt เอเจนต์เฟส 4" },
  AGENT_CRITIC: { description: "รายงาน continuity/emotion/proof/marketing (JSON)", usage: "system prompt เอเจนต์เฟส 5" },
  NIS_PLOT: { description: "ตรวจช่องโหว่โครงเรื่อง/ความต่อเนื่อง ทุกข้อมีข้อความขัดแย้งอ้างอิง", usage: "รันกับต้นฉบับเต็มหรือหลายบท" },
  NIS_CHARACTER: { description: "ตรวจความสม่ำเสมอ/เสียงเพี้ยนของตัวละคร พร้อมข้อความที่ตั้งไว้-vs-ขัดกัน", usage: "รันกับต้นฉบับเต็ม (+ character bible)" },
  NIS_PACING: { description: "จังหวะรายบทจากสัญญาณรูปธรรม หาช่วงอืด + ไคลแมกซ์รวบรัด", usage: "รันกับต้นฉบับที่ประกอบแล้ว" },
  NIS_FORESHADOW: { description: "จับคู่ setup-payoff ชี้ปืนที่ไม่ลั่นและการเปิดเผยที่ไม่ปูทาง", usage: "รันกับต้นฉบับเต็มเพื่อตรวจการปูทาง" },
  NIS_DIALOGUE: { description: "ช่วงหัวพูดกัน อธิบายโต้ง ๆ เสียงเหมือนกัน (คู่กับ Thai Analyzer)", usage: "รันกับบทที่บทสนทนาเยอะ" },
  NIS_POV: { description: "head-hop กาลหลุด ระยะ deep-POV รู้ในสิ่งที่รู้ไม่ได้ — อ้างข้อความทุกข้อ", usage: "รันกับต้นฉบับเต็มเพื่อล็อกมุมมอง/กาล" },
  NIS_SHOW: { description: "จับการบอกอารมณ์/สรุปตรง ๆ พร้อมตัวอย่างเขียนใหม่ที่แสดง เว้นช่วงเชื่อมที่ถูกต้อง", usage: "รันกับฉากที่รู้สึกแบน" },
  NIS_THEME: { description: "ตามรอย motif ทุกครั้งพร้อมอ้างข้อความ จับ motif ที่หาย/แก่นเรื่องโต้ง ๆ", usage: "รันกับต้นฉบับที่ประกอบแล้ว" },
};
